services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin1234
      - MONGO_INITDB_DATABASE=CSI
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: ./Server
    working_dir: /app
    volumes:
      - ./Server:/app
    ports:
      - "10500:10500"
    command: yarn dev
    environment:
      - DATABASE_URL=mongodb://admin:admin1234@mongodb:27017/CSI?authSource=admin
    depends_on:
      - mongodb

  client:
    build:
      context: ./CSI402/learning-project
    working_dir: /app
    volumes:
      - ./CSI402/learning-project:/src
    ports:
      - "3100:3000"
    command: yarn dev
    depends_on:
      - server

volumes:
  mongo-data:
