import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CSI402-Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-slate-100 h-[100dvh] w-[100dvw] flex flex-col justify-start items-center ">
          <header className="w-full h-[4rem] bg-gradient-to-r from-blue-500 to-blue-700 shadow-md flex items-center">
            <ul className="flex justify-center items-center w-full gap-16 text-white font-semibold">
              <Link href={"/"} className="hover:underline cursor-pointer">
                Sign Up
              </Link>
              <Link href={"/create"} className="hover:underline cursor-pointer">
                Create Temp Accounts
              </Link>
              <Link href={"/csi402"} className="hover:underline cursor-pointer">
                Temp Accounts
              </Link>
              <li className="hover:underline cursor-pointer">Menu C</li>
            </ul>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
